-- Add new non-food aisles
INSERT INTO public.aisles (name, icon, position) VALUES
  ('Bébé et puériculture', '👶', 16),
  ('Animalerie', '🐕', 17),
  ('Papeterie et bureau', '📝', 18),
  ('Jardin et extérieur', '🌱', 19),
  ('Maison et cuisine', '🏠', 20);

-- Get the aisle IDs for the new and existing aisles
-- We'll use a CTE approach to insert products with the correct aisle IDs

-- Insert non-food products for "Hygiène et entretien" (existing)
INSERT INTO public.shopping_products (name, aisle_id, user_id, family_id)
SELECT name, aisle_id, NULL, NULL FROM (
  VALUES
    -- Hygiène corporelle
    ('Savon liquide', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Savon solide', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Gel douche', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Shampoing', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Après-shampoing', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Déodorant', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Dentifrice', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Brosse à dents', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Fil dentaire', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Bain de bouche', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Rasoir', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Mousse à raser', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Crème hydratante', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Crème solaire', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Lait corporel', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Coton-tiges', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Cotons démaquillants', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Démaquillant', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Mouchoirs', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Papier toilette', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Serviettes hygiéniques', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Tampons', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Protège-slips', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Préservatifs', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Pansements', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Antiseptique', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Thermomètre', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Paracétamol', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Lime à ongles', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Coupe-ongles', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Crème pour les mains', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Crème pour les pieds', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Lingettes corporelles', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Eau de cologne', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Parfum', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    -- Produits d'entretien
    ('Liquide vaisselle', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Tablettes lave-vaisselle', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Sel régénérant lave-vaisselle', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Liquide de rinçage', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Lessive liquide', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Lessive en poudre', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Lessive en capsules', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Adoucissant', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Détachant', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Javel', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Nettoyant multi-surfaces', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Nettoyant vitres', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Nettoyant salle de bain', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Nettoyant WC', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Nettoyant four', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Nettoyant sol', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Désinfectant', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Déboucheur', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Anticalcaire', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Éponges', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Éponges à récurer', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Brosses vaisselle', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Gants ménagers', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Serpillière', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Balai', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Balai-brosse', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Pelle à poussière', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Sacs poubelle 30L', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Sacs poubelle 50L', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Sacs poubelle 100L', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Sacs congélation', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Film alimentaire', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Papier aluminium', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Papier cuisson', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Essuie-tout', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Chiffons microfibres', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Lavettes', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Désodorisant', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Bougies parfumées', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Allumettes', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Briquet', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Piles AA', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Piles AAA', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Ampoules LED', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Insecticide', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Anti-moustiques', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Souricide', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien')),
    ('Cirage chaussures', (SELECT id FROM aisles WHERE name = 'Hygiène et entretien'))
) AS products(name, aisle_id);

-- Insert products for "Bébé et puériculture"
INSERT INTO public.shopping_products (name, aisle_id, user_id, family_id)
SELECT name, aisle_id, NULL, NULL FROM (
  VALUES
    ('Couches taille 1', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Couches taille 2', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Couches taille 3', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Couches taille 4', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Couches taille 5', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Couches-culottes', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Lingettes bébé', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Liniment', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Crème change', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Lait de toilette bébé', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Gel lavant bébé', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Shampoing bébé', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Huile de massage bébé', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Sérum physiologique', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Lait infantile 1er âge', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Lait infantile 2ème âge', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Lait de croissance', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Petit pot légumes', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Petit pot fruits', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Petit pot viande', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Compote bébé', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Céréales bébé', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Biscuits bébé', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Eau minérale bébé', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Biberon', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Tétine biberon', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Sucette', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Attache-sucette', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Goupillon biberon', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Stérilisateur', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Bavoirs', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Cuillères bébé', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Assiette bébé', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Gobelet anti-fuite', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture')),
    ('Anneau de dentition', (SELECT id FROM aisles WHERE name = 'Bébé et puériculture'))
) AS products(name, aisle_id);

-- Insert products for "Animalerie"
INSERT INTO public.shopping_products (name, aisle_id, user_id, family_id)
SELECT name, aisle_id, NULL, NULL FROM (
  VALUES
    ('Croquettes chien', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Croquettes chat', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Pâtée chien', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Pâtée chat', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Friandises chien', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Friandises chat', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Os à mâcher', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Litière chat', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Sacs à crottes', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Shampooing chien', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Shampooing chat', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Antiparasitaire chien', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Antiparasitaire chat', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Collier antipuces', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Brosse pour animaux', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Jouet chien', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Jouet chat', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Griffoir chat', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Coussin pour animaux', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Gamelle', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Fontaine à eau', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Laisse', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Collier', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Harnais', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Cage de transport', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Graines pour oiseaux', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Nourriture poisson', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Nourriture rongeur', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Foin', (SELECT id FROM aisles WHERE name = 'Animalerie')),
    ('Litière rongeur', (SELECT id FROM aisles WHERE name = 'Animalerie'))
) AS products(name, aisle_id);

-- Insert products for "Papeterie et bureau"
INSERT INTO public.shopping_products (name, aisle_id, user_id, family_id)
SELECT name, aisle_id, NULL, NULL FROM (
  VALUES
    ('Stylos bille', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Stylos feutre', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Surligneurs', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Crayons à papier', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Crayons de couleur', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Feutres', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Gomme', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Taille-crayon', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Règle', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Équerre', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Compas', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Calculatrice', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Cahier petit format', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Cahier grand format', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Bloc-notes', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Post-it', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Ramette papier A4', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Papier couleur', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Enveloppes', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Classeur', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Chemises cartonnées', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Pochettes plastiques', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Trombones', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Punaises', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Agrafeuse', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Agrafes', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Perforatrice', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Scotch', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Colle', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Colle en stick', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Ciseaux', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Cutter', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Étiquettes autocollantes', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Correcteur liquide', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Ruban correcteur', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Marqueurs permanents', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Feuilles à dessin', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Peinture gouache', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Pinceaux', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau')),
    ('Papier crépon', (SELECT id FROM aisles WHERE name = 'Papeterie et bureau'))
) AS products(name, aisle_id);

-- Insert products for "Jardin et extérieur"
INSERT INTO public.shopping_products (name, aisle_id, user_id, family_id)
SELECT name, aisle_id, NULL, NULL FROM (
  VALUES
    ('Terreau universel', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Terreau pour plantes fleuries', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Engrais universel', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Engrais tomates', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Engrais gazon', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Graines de gazon', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Graines de tomates', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Graines de radis', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Graines de salade', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Graines de carottes', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Graines aromatiques', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Bulbes fleurs', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Pot de fleurs', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Jardinière', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Arrosoir', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Tuyau arrosage', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Pistolet arrosage', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Gants de jardinage', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Sécateur', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Pelle de jardin', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Râteau', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Binette', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Désherbant', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Anti-limaces', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Tuteurs', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Ficelle de jardin', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Charbon de bois BBQ', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Allume-feu', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Bouteille de gaz BBQ', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur')),
    ('Torches de jardin', (SELECT id FROM aisles WHERE name = 'Jardin et extérieur'))
) AS products(name, aisle_id);

-- Insert products for "Maison et cuisine"
INSERT INTO public.shopping_products (name, aisle_id, user_id, family_id)
SELECT name, aisle_id, NULL, NULL FROM (
  VALUES
    ('Assiettes jetables', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Gobelets jetables', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Couverts jetables', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Serviettes en papier', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Nappe en papier', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Pailles', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Cure-dents', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Pics apéritif', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Moules à gâteau', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Caissettes cupcakes', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Bougies anniversaire', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Décoration gâteau', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Ficelle cuisine', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Brochettes bois', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Torchons cuisine', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Maniques', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Tablier cuisine', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Bocaux conservation', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Boîtes hermétiques', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Boîtes à épices', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Distributeur essuie-tout', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Range-couverts', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Égouttoir vaisselle', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Poubelle cuisine', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Bac à glaçons', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Ouvre-boîte', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Tire-bouchon', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Décapsuleur', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Économe', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Presse-agrumes', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Cintres', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Pinces à linge', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Étendoir à linge', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Table à repasser', (SELECT id FROM aisles WHERE name = 'Maison et cuisine')),
    ('Housse table à repasser', (SELECT id FROM aisles WHERE name = 'Maison et cuisine'))
) AS products(name, aisle_id);